version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_DB=postgres
    networks:
      - postgres_internal_network
    
  app:
    build: .
    depends_on:
      - postgres
    networks:
      - postgres_internal_network
  
networks:
  postgres_internal_network:
    name: postgres_internal_network